all:                                                                                                                                                                                                        
	gcc main.c myLinkedList.c -o my_linked_list.out

clean:
	@rm -f *.out