all:                                                                                                                                                                                                        
	gcc main.c myArray.c -o my_array.out

clean:
	@rm -f *.out